name: supply_chain_app
channels:
  - conda-forge
dependencies:
  - python=3.11
  - glpk
  - pip
  - pip:
      - openpyxl
      - matplotlib==3.10.8
      - numpy==2.4.0
      - pandas==2.3.3
      - pyomo==6.9.5
      - seaborn==0.13.2
      - streamlit==1.37.1
